# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param1', models.FloatField(max_length=10)),
                ('param2', models.FloatField(max_length=10)),
                ('param3', models.FloatField(max_length=10)),
                ('epsilon', models.FloatField(max_length=10)),
            ],
        ),
    ]
